version: '3.8'

services:
  api:
    build:
      context: ..                 
      dockerfile: NomNom.API/Dockerfile 
    ports:
      - "5300:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__User=nomnom
      - RabbitMq__Password=nomnom
    depends_on:
      - db
      - cache
      - rabbitmq
    networks:
      - nomnom-network

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyStr0ng!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql           
      - ./init-sql:/docker-entrypoint-initdb.d  
    networks:
      - nomnom-network
    

  cache:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    networks:
      - nomnom-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nomnom-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: nomnom
      RABBITMQ_DEFAULT_PASS: nomnom
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - nomnom-network

volumes:
  mssql_data:
  rabbitmq_data:
  
networks:
  nomnom-network:
    driver: bridge